version: '3.6'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - "./database:/var/lib/mysql"
  db_pma:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: root
      PMA_PASSWORD: password
  mail:
    image: mailhog/mailhog:latest
    ports:
    - 8081:8025
  www:
    depends_on:
    - db
    - mail
    container_name: "webserver"
    image: php:apache
    volumes:
    - "./www:/var/www/html"
    ports:
    - 8080:80
